# This is a basic workflow to help you get started with Actions

name: Build and deploy Angular Application to EC2

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: 
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@master
#     - name: Set up Node.js version
#       uses: actions/setup-node@v1
#       with:
#         node-version: '12.x'

#     - name: npm install, build, and test
#       run: |
#         npm install
#         npm run-script build --prod --build-optimizer --if-present
    steps:
    - name: 'SCP to AWS EC2'
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.AWS_PEM }}
        port: 22
        source: "src"
        target: "/var/www/e-commerce-store/dist"
